# Generated by Django 6.0.5 on 2026-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='blocked_keywords',
            field=models.TextField(blank=True, help_text='Palabras separadas por comas. Se excluirán artículos que las contengan en etiquetas, título o resumen.'),
        ),
    ]
