# Generated by Django 6.0.5 on 2026-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_medio_feed_medio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='favicon_url',
        ),
        migrations.AddField(
            model_name='medio',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
    ]
