# Generated by Django 6.0.5 on 2026-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_remove_feed_favicon_url_medio_favicon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema (según dispositivo)')], default='system', max_length=10)),
                ('articles_retention_days', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
            },
        ),
    ]
